controller_list:
  - name: fake_arm_exoscope_controller
    type: $(arg fake_execution_type)
    joints:
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
      - lbr_joint_7
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
      - lbr_joint_7
initial:  # Define initial robot poses per group
  - group: arm_exoscope
    pose: home
  - group: arm
    pose: home