controller_list:
  - name: fake_arm_gripper_controller
    joints:
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
      - lbr_joint_7
      - gripper_joint_1
      - gripper_joint_2
initial:  # Define initial robot poses.
  - group: arm_gripper
    pose: home