# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_gripper
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7
    - gripper_joint_1
    - gripper_joint_2
    - gripper_joint_3
    - gripper_joint_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []